/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateRecordValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Model
   *
   */
  model: string;
  /**
   * Parameters
   *
   */
  parameters: string;
  /**
   * External ID
   *
   */
  externalId?: string;
}

/**
 * Create Record
 *
 * @description Create a new record of a given type.
 */
export const createRecord = {
  key: "createRecord",
  perform: async <TReturn,>(values: CreateRecordValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.odoo.createRecord({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    model: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    parameters: {
      inputType: "code",
      collection: undefined,
      default: ``,
      required: true,
    },
    externalId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: { data: 25 },
  examplePerformSafety: "notAllowed",
  performSafety: "notAllowed",
} as const;
