/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteRecordByIdValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Model
   *
   */
  model: string;
  /**
   * Record ID
   *
   */
  id: string;
}

/**
 * Delete Record By ID
 *
 * @description Delete a record by its numerical ID.
 */
export const deleteRecordById = {
  key: "deleteRecordById",
  perform: async <TReturn,>(
    values: DeleteRecordByIdValues,
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.odoo.deleteRecordById({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    model: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    id: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: { data: true },
  examplePerformSafety: "notAllowed",
  performSafety: "notAllowed",
} as const;
