/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetRecordByIdValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Model
   *
   */
  model: string;
  /**
   * Record ID
   *
   */
  id: string;
}

/**
 * Get Record By ID
 *
 * @description Fetch a record by its numerical ID.
 */
export const getRecordById = {
  key: "getRecordById",
  perform: async <TReturn,>(values: GetRecordByIdValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.odoo.getRecordById({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    model: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    id: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      id: 12,
      lang: "en_US",
      name: "John Doe",
      email: "john.doe@example.com",
      website_url: "/partners/john-doe-12",
      display_name: "John Doe",
    },
  },
  examplePerformSafety: "notAllowed",
  performSafety: "notAllowed",
} as const;
