/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetRecordByExternalIdValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * External ID
   *
   */
  externalId: string;
}

/**
 * Get Record by External ID
 *
 * @description Get a record by its external ID.
 */
export const getRecordByExternalId = {
  key: "getRecordByExternalId",
  perform: async <TReturn,>(
    values: GetRecordByExternalIdValues,
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.odoo.getRecordByExternalId({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    externalId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      id: 12,
      lang: "en_US",
      name: "John Doe",
      email: "john.doe@example.com",
      website_url: "/partners/john-doe-12",
      display_name: "John Doe",
    },
  },
  examplePerformSafety: "notAllowed",
  performSafety: "notAllowed",
} as const;
