/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { createRecord } from "./createRecord";
import { deleteRecordById } from "./deleteRecordById";
import { getRecordByExternalId } from "./getRecordByExternalId";
import { getRecordById } from "./getRecordById";
import { listModelFields } from "./listModelFields";
import { listModels } from "./listModels";
import { listRecords } from "./listRecords";
import { rawHttpRequest } from "./rawHttpRequest";
import { rawRequest } from "./rawRequest";
import { setExternalId } from "./setExternalId";
import { updateRecord } from "./updateRecord";

export default {
  createRecord,
  deleteRecordById,
  getRecordByExternalId,
  getRecordById,
  listModelFields,
  listModels,
  listRecords,
  rawHttpRequest,
  rawRequest,
  setExternalId,
  updateRecord,
};
