/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListRecordsValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Model
   *
   */
  model: string;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Limit
   *
   */
  limit?: string;
  /**
   * Offset
   *
   */
  offset?: string;
}

/**
 * List Records
 *
 * @description Fetch a list of records of a given type.
 */
export const listRecords = {
  key: "listRecords",
  perform: async <TReturn,>(values: ListRecordsValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.odoo.listRecords({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    model: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    offset: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: [
      {
        id: 12,
        lang: "en_US",
        name: "John Doe",
        email: "john.doe@example.com",
        website_url: "/partners/john-doe-12",
        display_name: "John Doe",
      },
    ],
  },
  examplePerformSafety: "notAllowed",
  performSafety: "notAllowed",
} as const;
