/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListModelsValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Limit
   *
   */
  limit?: string;
  /**
   * Offset
   *
   */
  offset?: string;
  /**
   * Name Search
   *
   */
  nameSearch?: string;
  /**
   * Model Search
   *
   */
  modelSearch?: string;
}

/**
 * List Models
 *
 * @description Fetch a list of models installed in the Odoo database.
 */
export const listModels = {
  key: "listModels",
  perform: async <TReturn,>(values: ListModelsValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.odoo.listModels({ ...values })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    offset: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    nameSearch: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    modelSearch: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: [
      {
        id: 87,
        name: "Bank Accounts",
        model: "res.partner.bank",
        state: "base",
        modules: "account, base, l10n_us",
        display_name: "Bank Accounts",
      },
      {
        id: 85,
        name: "Industry",
        model: "res.partner.industry",
        state: "base",
        modules: "base",
        display_name: "Industry",
      },
    ],
  },
  examplePerformSafety: "notAllowed",
  performSafety: "notAllowed",
} as const;
