/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListModelFieldsValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Model
   *
   */
  model: string;
}

/**
 * List Model Fields
 *
 * @description List all fields for a given model.
 */
export const listModelFields = {
  key: "listModelFields",
  perform: async <TReturn,>(
    values: ListModelFieldsValues,
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.odoo.listModelFields({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    model: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      is_seo_optimized: {
        name: "is_seo_optimized",
        type: "boolean",
        store: false,
        manual: false,
        string: "SEO optimized",
        depends: [],
        readonly: true,
        required: false,
        sortable: false,
        searchable: false,
        change_default: false,
        company_dependent: false,
      },
      website_meta_title: {
        name: "website_meta_title",
        trim: true,
        type: "char",
        store: true,
        manual: false,
        string: "Website meta title",
        depends: [],
        readonly: false,
        required: false,
        sortable: true,
        translate: true,
        searchable: true,
        change_default: false,
        company_dependent: false,
      },
    },
  },
  examplePerformSafety: "notAllowed",
  performSafety: "notAllowed",
} as const;
