/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface RawHttpRequestValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * URL
   *
   */
  url: string;
  /**
   * Method
   *
   */
  method: string;
  /**
   * Data
   *
   */
  data?: string;
  /**
   * Form Data
   *
   */
  formData?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * File Data
   *
   */
  fileData?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * File Data File Names
   *
   */
  fileDataFileNames?:
    Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Query Parameter
   *
   */
  queryParams?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Header
   *
   */
  headers?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Response Type
   *
   * @default json
   */
  responseType?: string;
  /**
   * Timeout
   *
   */
  timeout?: string;
  /**
   * Retry Delay (ms)
   *
   * @default 0
   */
  retryDelayMS?: string;
  /**
   * Retry On All Errors
   *
   * @default false
   */
  retryAllErrors?: boolean;
  /**
   * Max Retry Count
   *
   * @default 0
   */
  maxRetries?: string;
  /**
   * Use Exponential Backoff
   *
   * @default false
   */
  useExponentialBackoff?: boolean;
}

/**
 * Raw Request (API Key)
 *
 * @description Send a raw HTTP request to the Odoo JSON-2 API. Requires the API Key connection.
 */
export const rawHttpRequest = {
  key: "rawHttpRequest",
  perform: async <TReturn,>(values: RawHttpRequestValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.odoo.rawHttpRequest({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    url: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    method: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    data: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    formData: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    fileData: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    fileDataFileNames: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    queryParams: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    headers: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    responseType: {
      inputType: "string",
      collection: undefined,
      default: `json`,
    },
    timeout: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    retryDelayMS: {
      inputType: "string",
      collection: undefined,
      default: `0`,
    },
    retryAllErrors: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    maxRetries: {
      inputType: "string",
      collection: undefined,
      default: `0`,
    },
    useExponentialBackoff: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
  },
  examplePayload: {},
  examplePerformSafety: "notAllowed",
  performSafety: "notAllowed",
} as const;
