/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface RawRequestValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Model
   *
   */
  model: string;
  /**
   * Method
   *
   */
  method: string;
  /**
   * Parameters
   *
   * @default [[\\"read\\"]]
   */
  parameters?: string;
}

/**
 * Raw Request (Basic Auth)
 *
 * @description Issue any execute_kw action against the Odoo XML-RPC API. Requires the Basic Authentication (Deprecated) connection.
 */
export const rawRequest = {
  key: "rawRequest",
  perform: async <TReturn,>(values: RawRequestValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.odoo.rawRequest({ ...values })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    model: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    method: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    parameters: {
      inputType: "code",
      collection: undefined,
      default: `[["read"]]`,
    },
  },
  examplePayload: {},
  examplePerformSafety: "notAllowed",
  performSafety: "notAllowed",
} as const;
