/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface SetExternalIdValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Model
   *
   */
  model: string;
  /**
   * Record ID
   *
   */
  id: string;
  /**
   * External ID
   *
   */
  externalId: string;
}

/**
 * Set External ID
 *
 * @description Add an external ID to a record that does not have one.
 */
export const setExternalId = {
  key: "setExternalId",
  perform: async <TReturn,>(values: SetExternalIdValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.odoo.setExternalId({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    model: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    id: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    externalId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: { data: 21943 },
  examplePerformSafety: "notAllowed",
  performSafety: "notAllowed",
} as const;
