/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UpdateRecordValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Model
   *
   */
  model: string;
  /**
   * Record ID
   *
   */
  id: string;
  /**
   * Parameters
   *
   */
  parameters: string;
}

/**
 * Update Record
 *
 * @description Update an existing record of a given type.
 */
export const updateRecord = {
  key: "updateRecord",
  perform: async <TReturn,>(values: UpdateRecordValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.odoo.updateRecord({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    model: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    id: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    parameters: {
      inputType: "code",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: { data: true },
  examplePerformSafety: "notAllowed",
  performSafety: "notAllowed",
} as const;
