[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$XOv9XyvF.P9/L8U4JwQAYA$/Ss/KzCB2ujQGcgz6SHDkjbO0HaNR3x8S4hNqJIf7pO8ykIY1E8rRSl50se4Zh78mmY00Q7PXecpYmyXaHhIMA

