[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$qpWyNiZkbA0hBGAsxVhLCQ$nvfBvJVhG4a49AY5ytMXKNlXSwBc9ETrKzskxIaN139MDBgKQifY2Mp0V0/PWVp8V.ZIbVYrS7mfoyocsBk4AQ
