[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$mfMeQ6g1pjQmJOSc0zonJA$aamYyolh39qLEcH9MwwT6tBldBcdAOPKFsN7u4QPvzhCz5WkJJtCcQc8ppMwSpX3e4fILe3V4t2ZtdJc4IPGpQ

