/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { pollChangesTrigger } from "./pollChangesTrigger";

export default {
  pollChangesTrigger,
};
