/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type { Connection } from "@prismatic-io/spectral/dist/types";

export interface PollChangesTriggerValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Model
   *
   */
  model: string;
  /**
   * Show New Records
   *
   * @default true
   */
  showNewRecords?: boolean;
  /**
   * Show Updated Records
   *
   * @default true
   */
  showUpdatedRecords?: boolean;
}

/**
 * Polls an Odoo model for records whose `write_date` is at or after the last poll. Records whose `create_date` is also after the last poll go to the `created` bucket; older records modified since the last poll go to `updated`.
 *
 * @description Polls an Odoo model for records whose `write_date` is at or after the last poll. Records whose `create_date` is also after the last poll go to the `created` bucket; older records modified since the last poll go to `updated`.
 * This object is used to support type hinting.
 */
export const pollChangesTrigger = {
  key: "pollChangesTrigger",
  perform: <TReturn,>(_values: PollChangesTriggerValues): Promise<TReturn> =>
    Promise.resolve<TReturn>({} as TReturn),
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    model: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    showNewRecords: {
      inputType: "boolean",
      collection: undefined,
      default: `true`,
    },
    showUpdatedRecords: {
      inputType: "boolean",
      collection: undefined,
      default: `true`,
    },
  },
} as const;

/**
 * Polls an Odoo model for records whose `write_date` is at or after the last poll. Records whose `create_date` is also after the last poll go to the `created` bucket; older records modified since the last poll go to `updated`. Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const odooPollChangesTrigger = (values: {
  connection:
    | {
        value: Connection;
      }
    | ConfigVarExpression;
  model:
    | {
        value: string;
      }
    | ConfigVarExpression;
  showNewRecords?:
    | {
        value: boolean;
      }
    | ConfigVarExpression;
  showUpdatedRecords?:
    | {
        value: boolean;
      }
    | ConfigVarExpression;
}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "odoo",
        true,
        context.componentRegistry,
      );
    },
    key: "pollChangesTrigger",
    values,
  } as const;
};
