/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { selectModel } from "./selectModel";
import { selectRecordById } from "./selectRecordById";

export default {
  selectModel,
  selectRecordById,
};
