/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Name Search
   *
   */
  nameSearch?: string;
  /**
   * Model Search
   *
   */
  modelSearch?: string;
}

/**
 * Select Model
 *
 * @description A picklist of models in the Odoo database.
 * This object is used to support type hinting.
 */
export const selectModel = {
  key: "selectModel",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "picklist",
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    nameSearch: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    modelSearch: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;

/**
 * Select Model DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const odooSelectModel = (
  stableKey: string,
  values: {
    connection: ConfigVarExpression;
    nameSearch?: { value: string } | TemplateExpression | ConfigVarExpression;
    modelSearch?: { value: string } | TemplateExpression | ConfigVarExpression;
  },
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "odoo",
          true,
          context.componentRegistry,
        );
      },
      key: "selectModel",
      values,
    },
  });
};
