/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import actions from "./actions";
import connections from "./connections";
import dataSources from "./dataSources";
import triggers from "./triggers";

export { actions, connections, dataSources, triggers };

export default {
  key: "odoo",
  public: true,
  signature: "f0499f61b215af99b9cb41f2cd918ceec9fc6fcc",
  actions,
  dataSources,
  connections,
  triggers,
} as const;
