/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { odooApiKey } from "./odooApiKey";
import { odooBasicAuth } from "./odooBasicAuth";

export default {
  odooApiKey,
  odooBasicAuth,
};
