/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface OdooBasicAuthValues {
  /**
   * Odoo Base URL
   *
   */
  baseUrl: string;
  /**
   * Server Port
   *
   */
  port?: string;
  /**
   * Odoo Database Name
   *
   */
  db: string;
  /**
   * Username
   *
   */
  username: string;
  /**
   * Password or API Key
   *
   */
  password: string;
}

/**
 * Basic Authentication (Deprecated)
 *
 * @comments Authenticate using a username and password against Odoo's XML-RPC API. Maintained for backwards compatibility with existing integrations. Odoo will drop XML-RPC support in 19.1 (mid-2026); use the API Key connection for new integrations.
 * This object is used to support type hinting.
 */
export const odooBasicAuth = {
  key: "odooBasicAuth",
  perform: (_values: OdooBasicAuthValues): Promise<void> => Promise.resolve(),
  inputs: {
    baseUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    port: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    db: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    username: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    password: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * Basic Authentication (Deprecated) Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const odooOdooBasicAuth = (
  stableKey: string,
  values: {
    baseUrl:
      | ((
          | {
              value: string;
            }
          | ConfigVarExpression
        ) &
          ConfigVarVisibility & { writeOnly?: true })
      | (ConfigVarVisibility & { writeOnly?: true });
    port?:
      | ((
          | {
              value: string;
            }
          | ConfigVarExpression
        ) &
          ConfigVarVisibility & { writeOnly?: true })
      | (ConfigVarVisibility & { writeOnly?: true });
    db:
      | ((
          | {
              value: string;
            }
          | ConfigVarExpression
        ) &
          ConfigVarVisibility & { writeOnly?: true })
      | (ConfigVarVisibility & { writeOnly?: true });
    username:
      | ((
          | {
              value: string;
            }
          | ConfigVarExpression
        ) &
          ConfigVarVisibility & { writeOnly?: true })
      | (ConfigVarVisibility & { writeOnly?: true });
    password:
      | ((
          | {
              value: string;
            }
          | ConfigVarExpression
        ) &
          ConfigVarVisibility & { writeOnly?: true })
      | (ConfigVarVisibility & { writeOnly?: true });
  },
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "odoo",
          true,
          context.componentRegistry,
        );
      },
      key: "odooBasicAuth",
      values,
    },
  });
};
