/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface OdooApiKeyValues {
  /**
   * Odoo Base URL
   *
   */
  baseUrl: string;
  /**
   * Server Port
   *
   */
  port?: string;
  /**
   * Odoo Database Name
   *
   */
  db: string;
  /**
   * API Key
   *
   */
  apiKey: string;
}

/**
 * API Key
 *
 * @comments Authenticate requests to Odoo using an API key.
 * This object is used to support type hinting.
 */
export const odooApiKey = {
  key: "odooApiKey",
  perform: (_values: OdooApiKeyValues): Promise<void> => Promise.resolve(),
  inputs: {
    baseUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    port: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    db: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    apiKey: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * API Key Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const odooOdooApiKey = (
  stableKey: string,
  values: {
    baseUrl:
      | ((
          | {
              value: string;
            }
          | ConfigVarExpression
        ) &
          ConfigVarVisibility & { writeOnly?: true })
      | (ConfigVarVisibility & { writeOnly?: true });
    port?:
      | ((
          | {
              value: string;
            }
          | ConfigVarExpression
        ) &
          ConfigVarVisibility & { writeOnly?: true })
      | (ConfigVarVisibility & { writeOnly?: true });
    db:
      | ((
          | {
              value: string;
            }
          | ConfigVarExpression
        ) &
          ConfigVarVisibility & { writeOnly?: true })
      | (ConfigVarVisibility & { writeOnly?: true });
    apiKey:
      | ((
          | {
              value: string;
            }
          | ConfigVarExpression
        ) &
          ConfigVarVisibility & { writeOnly?: true })
      | (ConfigVarVisibility & { writeOnly?: true });
  },
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "odoo",
          true,
          context.componentRegistry,
        );
      },
      key: "odooApiKey",
      values,
    },
  });
};
